apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bolttickets
type: Opaque
data:
  password: cG9zdGdyZXM=  # base64 of 'postgres'
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: bolttickets
type: Opaque
data:
  admin-password: YWRtaW4=  # base64 of 'admin'